USE PRIMEIRO_DB --É IMPORTANTE USAR O COMANDO 'USE' (SEGUIDO DO NOME DO BD DESEJADO) COMO BOA PRATICA PARA EVITAR CRIAR UMA TABELA EM UM BANCO DE DADOS ERRADO

CREATE TABLE CLIENTES -- COMANDO CRIA UMA TABELA
(      -- USAMOS PARESTESES PARA INICIAR E FECHAR O COMANDO 
	ID_CLIENTE INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL,
	DATA_CADASTRO DATETIME,
	EMAIL VARCHAR(20) UNIQUE 
)
