USE PRIMEIRO_DB

UPDATE CLIENTES -- ATUALIZA OS REGISTROS NAS COLUNAS
SET NOME = 'Zé das Couve' -- USAMOS SET SEGUIDO DA COLUNA PARA ALTERAR E UAL A ALTERAÇÃO DESEJAMOS FAZER
WHERE ID_CLIENTE = 1 -- ONDE VAMOS FAZER APLICAR A ALTERAÇÃO.

