USE ContosoRetailDW

SELECT * FROM FactSales -- O ASTERISCO TRAZ TODOS OS CAMPOS DE UMA TABELA, NÃO É UMA BOA PRATICA FAZER ESSE TIPO DE SELECT POIS ALGUNS 
-- BANCOS DE DADOS POSSUEM MILHARES DE LINHAS E ISSO PODE PREJUDICAR A PERFORMANCE DO BD.