USE ContosoRetailDW

SELECT
	[StoreKey] AS 'ID_LOJA'  -- USAMOS 'AS' PARA APELIDAR AS NOSSAS COLUNAS
	,[StoreName] AS 'NOME_LOJA'
	,[EmployeeCount] AS QUANTIDADE_FUNCIONARIOS  -- ESSE FORMATO SE ASPAS ('') TAMBÉM PODE SER UTILIZADO


FROM DimStore