USE ContosoRetailDW

SELECT 
	* 
FROM DimCustomer

ORDER BY FirstName DESC -- USAMOS ORDER BY PARA ORDENAR OS DADOS, LOGO APÓS ESCREVEMOS QUAL COLUNA ORDENAR E DEPOIS USAMOS ASC OU DESC
-- PARA SELECIONAR EM ORDEM ASCENDENTE OU DECRESCENTE