USE ContosoRetailDW
	--BUSCA O NOME COMPLETO EX: NOME AARON PAINTER
SELECT 
	FirstName + ' ' + LastName AS 'FULLNAME',
	* 
FROM DimEmployee
WHERE
	FirstName + ' ' + LastName LIKE 'AARON PAINTER' -- DIGITAMOS O NOME COMPLETO PARA FAZER A BUSCA DESEJADA

	--BUSCA O NOME NO COMEÇO. EX: NOME AARON
SELECT 
	FirstName + ' ' + LastName AS 'FULLNAME',
	* 
FROM DimEmployee
WHERE
	FirstName + ' ' + LastName LIKE 'AARON%' -- COLOCAMOS % NO FINAL DA STRING PARA BUSCAR O NOME NO INICIO

	--BUSCA EM QUALQUER LUGAR. EX: NOME AARON
SELECT 
	FirstName + ' ' + LastName AS 'FULLNAME',
	* 
FROM DimEmployee
WHERE
	FirstName + ' ' + LastName LIKE '%AARON%' -- COLOCAMOS % NO INICIO E % NO FINAL DA STRING

	--QUANDO TEMOS DUVIDAS PODEMOS PEDIR UMA QUERY COM OPÇÕES DE LETRAS 
SELECT 
	FirstName + ' ' + LastName AS 'FULLNAME',
	* 
FROM DimEmployee
WHERE
	FirstName + ' ' + LastName LIKE '%GON[ZS]ALE[ZS]%' -- COLOCAMOS % NO INICIO E % NO FINAL DA STRING E COLOCAMOS ENTRE COLCHETES[] AS LETRAS QUE ACHAMOS