USE ContosoRetailDW

SELECT
	SUM(SalesAmount) AS 'SOMA' -- COM O SUM SOMAMOS TODAS AS COLUNAS 
FROM FactSales

SELECT
	AVG(SalesAmount) AS 'MÉDIA' -- COM O AVG TEMOS A MÉDIA DAS COLUNAS
FROM FactSales

SELECT
	COUNT(SalesAmount) AS 'QTD DE LINHAS' -- COM O COUNT CONTAMOS TODAS AS LINHAS 
FROM FactSales

SELECT
	MAX(SalesAmount) AS 'MAXIMO' -- COM O MAX PEGAMOS O MAIOR VALOR APRESENTADO NA COLUNA
FROM FactSales

SELECT
	MIN(SalesAmount) AS 'MINIMO' -- COM O PEGAMOS O MENOR VALOR APRESENTADO NA COLUNA
FROM FactSales