USE ContosoRetailDW

SELECT 
	GETDATE() AS 'DATA ATUAL' -- ESSA FUNÇÃO PERMITE PUXAR A DATA E HORA ATUAL AUTOMATICAMENTE

SELECT
	GETDATE()+10 AS 'DATA ATUAL + 10 DIAS' -- CONSIGO ACRESCENTAR MAIS 10 DIAS EM NOSSA DATA COM ESSA FUNÇÃO

SELECT
	YEAR(GETDATE()) AS ANO

SELECT 
	MONTH(GETDATE()) AS MÊS

SELECT
	DAY(GETDATE()) AS DIA