USE ContosoRetailDW

SELECT 
	GETDATE() AS 'DATA ATUAL' -- ESSA FUNÇÃO PERMITE PUXAR A DATA E HORA ATUAL AUTOMATICAMENTE

SELECT
	GETDATE()+10 AS 'DATA ATUAL + 10 DIAS' -- CONSIGO ACRESCENTAR MAIS 10 DIAS EM NOSSA DATA COM ESSA FUNÇÃO

SELECT
	YEAR(GETDATE()) AS ANO -- COM ESSA FUNÇÃO CONEGUIMOS PUXAR SOMENTE O ANO

SELECT 
	MONTH(GETDATE()) AS MÊS -- COM ESSA FUNÇÃO CONEGUIMOS PUXAR SOMENTE O MES

SELECT
	DAY(GETDATE()) AS DIA -- COM ESSA FUNÇÃO CONEGUIMOS PUXAR SOMENTE O DIA

SELECT 
	*
FROM FactOnlineSales  -- CONSEGUIMOS FILTRAR USANDO A FUNÇÃO YEAR, MONTH E DAY JUNTAMENTE COM O WHERE, PARA PUXAR UMA DATA ESPECIFICA
WHERE
	YEAR(DateKey) = 2007 AND
	MONTH(DATEKEY) = 12 AND
	DAY(DateKey) = 31