-- DATADIFF (intervalo, data_inicio, data_final)
-- O DATEDIFF BUSCA A DIFERENÇA ENTRE AS DATAS

USE ContosoRetailDW

SELECT DATEDIFF(DAY, '2025-05-01', GETDATE()) AS DIA
SELECT DATEDIFF(MONTH, '2025-05-01', GETDATE()) AS MÊS


SELECT TOP 100
	S.DateKey, 
	GETDATE(),

FROM FactOnlineSales S
ORDER BY 1 DESC