-- END OF MONTH 

USE ContosoRetailDW

SELECT 
	EOMONTH(GETDATE()) AS 'FIM DO MÊS',
	GETDATE() AS 'DATA ATUAL',
	EOMONTH(GETDATE(), 1) AS 'ADICIONANDO UM MÊS',
	EOMONTH(GETDATE(), -1) AS 'SUBTRAINDO UM MÊS'