DECLARE @USER VARCHAR(30)
SET @USER = 'MARIA MARIA'

SELECT 
	@USER,
	LEN(@USER) -- FUNÇÃO LEN - FAZ A CONTAGEM DE CARACTERES
	RTRIM(@USER) -- FUNÇÃO RTRIM - RETIRA OS ESPAÇOS EM BRANCOS DA DIREITA
	LTRIM(@USER) -- FUNÇÃO LTRIM - RETIRA OS ESPAÇOS EM BRANCO DA ESQUERDA