DECLARE @USER VARCHAR(30)
SET @USER = 'MARIA MARIA'

SELECT 
	@USER,
	LEN(@USER), -- FUNÇÃO LEN - FAZ A CONTAGEM DE CARACTERES
	RTRIM(@USER), -- FUNÇÃO RTRIM - RETIRA OS ESPAÇOS EM BRANCOS DA DIREITA
	LTRIM(@USER), -- FUNÇÃO LTRIM - RETIRA OS ESPAÇOS EM BRANCO DA ESQUERDA
	TRIM(@USER), -- FUNÇÃO TRIM - RETIRA OS ESPAÇOS DE AMBOS OS LADOS
	UPPER(@USER), -- FUNÇÃO UPPER - DEIXA TODO O TEXTO EM LETRAS MAIUSCULAS
	LOWER(@USER) -- FUNÇÃO LOWER - DEIXA TODO O TEXTO EM LETRAS MINUSCULAS 
