DECLARE @USER VARCHAR(30)

SET @USER = ' JOÃO '

DECLARE @USER2 VARCHAR (30)
SET @USER2 = ' JOSÉ '

SELECT @USER + @USER2 AS NAME -- ESSA É UMA FORMA DE CONCATENAR AS INFORMAÇÕES DE VARIAVEIS 

SELECT CONCAT(@USER, @USER2, 'DA SILVA') AS NAMES -- PODEMOS CONCATENAR USANDO A FUNÇÃO CONCAT