SELECT 
	('SQL PARA ANALISE DE DADOS'),
	--(TEXTO PARA A SUBSITUIÇÃO, BUSCA DA PALAVRA PARA SUBISTITUIR, A PALAVRA OFICIAL)
	REPLACE('SQL PARA ANALISE DE DADOS', 'ANALISE', 'ANÁLISE') -- PARA SUBSTITUIR USAMOS A FUNÇÃO REPLACE

