SELECT 
	'SQL é mais legal que Power Bi',
	SUBSTRING('SQL é mais legal que Power Bi',1,3), --FUNÇÃO SUBSTRING (FRASE PARA EXTRAÇÃO, INICIO DA EXTRAÇÃO, QUANTOS CARACTERES VOCÊ QUER EXTRAIR))
	SUBSTRING('SQL é mais legal que Power Bi',22,9),
	LEFT('SQL é mais legal que Power Bi',3), -- PODEMOS USAR O LEFT, QUE JA INICIA DA ESQUERDA, DEPOIS SÓ PRECISAMOS INFORMAR A QTD DE CARACTERES
	RIGHT('SQL é mais legal que Power Bi',9) --PODEMOS USAR O RIGHT, QUE JA INICIA DA DIREITA PARA A ESQUEDA, DEPOIS SÓ PRECISAMOS INFORMAR A QTD DE CARACETERES
