--- SUBQUERY / SUBCONSULTA

USE ContosoRetailDW


SELECT
	AVG(SQ.VENDAS)
FROM
	(SELECT
	DATEPART(YEAR, S.DateKey) AS ANO,
	DATEPART(MONTH, S.DateKey) AS MES,
	SUM(S.SalesAmount) AS VENDAS
FROM FactSales AS S
GROUP BY DATEPART(YEAR, S.DATEKEY), DATEPART(MONTH, S.DATEKEY)
) AS SQ

--- CTE - COMMON TABLE EXPRESSION